name: sonarcloud IaC 
on:
  push:
    branches: 
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud_pre_terraform_tasks:
    runs-on: ubuntu-latest
    name: sonarcloud_pre_terraform_tasks
    env: 
      SONARCLOUD_ACCESS_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
    steps:
      - name: Install Terraform Binary
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.5

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Terraform Linting
        uses: actionshub/terraform-lint@1.0.0

      - name: Run Terrascan
        id: terrascan
        uses: accurics/terrascan-action@v1
        with:
          iac_type: 'terraform'
          iac_version: v14
