name: sonarcloud IaC 
on:
  push:
    branches: 
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud_pre_terraform_tasks:
    runs-on: ubuntu-latest
    name: sonarcloud_pre_terraform_tasks
    env: 
      SONARCLOUD_ACCESS_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
    steps:
      - name: Install Terraform Binary
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.5

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Terraform Linting
        uses: actionshub/terraform-lint@1.0.0

      - name: Terraform Security Check
        uses: triat/terraform-security-scan@v2.2.3
        with:
          tfsec_output_format: 'junit'
          tfsec_output_file: sonarcloud-tfsec.xml
          
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: sonarcloud-tfsec.xml
          
      - name: Terraform Validate
        run: |
          echo "==> running terraform validate"
          terraform init && terraform validate
          
      - name: Terraform Plan
        run: |
          echo "==> running terraform plan, please wait..."
          terraform init && terraform plan -out=plan.out && terraform show -json plan.out > plan.out.json

      - name: Terraform Compliance
        uses: terraform-compliance/github_action@0.3.0
        with:
          plan: plan.out.json
