name: sonarcloud IaC 
on:
  push:
    branches: 
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud_pre_terraform_tasks:
    runs-on: ubuntu-latest
    name: sonarcloud_pre_terraform_tasks
    env: 
      SONARCLOUD_ACCESS_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
    steps:
      - name: Install Terraform Binary
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.5

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Terraform Linting
        uses: actionshub/terraform-lint@1.0.0

      - name: Run tfsec
        uses: tfsec/tfsec-sarif-action@9a83b5c3524f825c020e356335855741fd02745f
        with:
          sarif_file: tfsec.sarif         

      - name: Perform Scan
        uses: ShiftLeftSecurity/scan-action@master
        env:
          WORKSPACE: ""
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCAN_AUTO_BUILD: true
        with:
          output: reports

      - uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports
        
      - name: Upload tfsec Report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: tfsec.sarif  
      
      - name: Terraform Validate
        run: |
          echo "==> running terraform validate"
          docker run –rm -t -v `pwd`:/src liamg/tfsec ./src –format JUnit > ./TFSecReport/junit.xml
          
      
